;; Live Power Pack

(require 'mwe-log-commands)
(require 'iy-go-to-char)
(require 'lively)
(require 'ace-jump-mode)
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
(live-load-config-file "quick-jump-conf.el")
(live-load-config-file "yasnippet-conf.el")
(live-load-config-file "undo-tree-conf.el")
(live-load-config-file "refheap-conf.el")
(live-load-config-file "scratch-conf.el")
(live-load-config-file "highlight-tail-conf.el")
(live-load-config-file "gist-conf.el")
(live-load-config-file "expand-region-conf.el")
(live-load-config-file "ace-jump-mode-conf.el")
(live-load-config-file "multiple-cursors-conf.el")
(live-load-config-file "undo-tree-conf.el")
(live-load-config-file "volatile-highlights-conf.el")
;;(live-load-config-file "browse-kill-ring-conf.el")
;;(live-load-config-file "git-gutter-conf.el")
;;(require 'mwe-log-commands)
;;(live-load-config-file "refheap-conf.el")
;;(live-load-config-file "scratch-conf.el")
;;(live-load-config-file "gist-conf.el")
